name: Test on macOS M1

on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  setup-ssh:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          brew install --cask docker
          open /Applications/Docker.app
        env:
          DISPLAY: :0

      - name: Install SSH server
        run: |
          brew install openssh
          sudo systemsetup -f -setremotelogin on

      - name: Start SSH server
        run: sudo launchctl load -w /System/Library/LaunchDaemons/ssh.plist

      - name: Generate SSH key
        run: |
          ssh-keygen -t rsa -b 4096 -f ./id_rsa -N ""
          cat ./id_rsa.pub >> ~/.ssh/authorized_keys
        id: ssh-key

      - name: Display SSH connection info
        run: |
          echo "Connect with the following command:"
          echo "ssh -i ./id_rsa $(whoami)@$(hostname)"
        env:
          SSH_KEY: ${{ steps.ssh-key.outputs.ssh-key }}

      - name: Keep runner alive for 30 minutes
        run: |
          echo "Runner will stay alive for 30 minutes. Connect using SSH."
          sleep 1800
